name: hitomi
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dynamic_color: ^1.6.5
  appwrite: ^9.0.0
  cached_network_image: ^3.2.3
  infinite_scroll_pagination: ^3.2.0
  shared_preferences: ^2.1.2
  provider: ^6.0.5
  gap: ^3.0.0
  local_auth: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
